### ISSUE TITLE
Reduce entanglement with cw-dao-dapp

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/cw-dao#50]
Currently, running a development environment (by our instructions) requires running the [frontend repo](https://github.com/DA0-DA0/cw-dao-dapp) in order to get a wasm address for one of your private keys. This links the two repos together a bit too tightly.

Ideally, developers should get a wasm address for their private key without the frontend repo.

**Comment by JakeHartnell** [comment]
We can just provide a default account for them if they want. This will be less of an issue when we use a Dockerized Juno instance as they will just be able to use their Juno accounts.

**Comment by JakeHartnell** [comment]
This is done, we have a default account.
